name: Coverage Test

on:
  push:
    branches-ignore: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, ratelimit]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build

      - name: Run ${{ matrix.test-type }} tests with coverage
        run: |
          npm run test:${{ matrix.test-type }}
        env:
          PUPPETEER_ARGS: "--no-sandbox,--disable-setuid-sandbox"

      - name: Upload coverage JSON summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.test-type }}
          path: coverage/tmp

  coverage-report:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download all coverage summaries
        uses: actions/download-artifact@v4
        with:
          path: coverage/tmp
          merge-multiple: true

      - name: Generate report
        run: npx c8 report --reporter=text >> $GITHUB_STEP_SUMMARY
